/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Elias
 */
public class LoginUsuarios extends javax.swing.JFrame {


    
    public LoginUsuarios() {
    initComponents();
    
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_alumno = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_dni = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_login_admin = new javax.swing.JButton();
        lbl_legajo = new javax.swing.JLabel();
        lbl_admin = new javax.swing.JLabel();
        txt_legajo = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        btn_admin = new javax.swing.JButton();
        btn_alumno = new javax.swing.JButton();
        btn_login_alumno = new javax.swing.JButton();
        lbl_contra = new javax.swing.JLabel();
        txt_contra = new javax.swing.JPasswordField();
        lbl_fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_registro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_alumno.setBackground(new java.awt.Color(255, 255, 255));
        lbl_alumno.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_alumno.setForeground(new java.awt.Color(255, 255, 255));
        lbl_alumno.setText("Alumno:");
        getContentPane().add(lbl_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, -1));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 110, -1));

        lbl_dni.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_dni.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dni.setText("DNI:");
        getContentPane().add(lbl_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, -1));

        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 110, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));

        btn_login_admin.setText("Iniciar Sesión");
        btn_login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_adminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 120, 40));

        lbl_legajo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_legajo.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_legajo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_legajo.setText("Legajo:");
        getContentPane().add(lbl_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, -1));

        lbl_admin.setBackground(new java.awt.Color(255, 255, 255));
        lbl_admin.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_admin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_admin.setText("Administrador:");
        getContentPane().add(lbl_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 120, -1));

        txt_legajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_legajoActionPerformed(evt);
            }
        });
        txt_legajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_legajoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));

        lbl_nombre.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre:");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 80, -1));

        lbl_apellido.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_apellido.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apellido.setText("Apellido:");
        getContentPane().add(lbl_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 80, -1));

        txt_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dniActionPerformed(evt);
            }
        });
        txt_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dniKeyTyped(evt);
            }
        });
        getContentPane().add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, -1));

        btn_admin.setText("Administrador");
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 120, 30));

        btn_alumno.setText("Alumno");
        btn_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 120, 30));

        btn_login_alumno.setText("Iniciar Sesión");
        btn_login_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_alumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 120, 40));

        lbl_contra.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_contra.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contra.setText("Contraseña:");
        getContentPane().add(lbl_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, -1));
        getContentPane().add(txt_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 110, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gettyimages-1171924854-640x640.jpg"))); // NOI18N
        lbl_fondo.setText("jLabel1");
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 360));

        menu_file.setText("Ir");

        menu_registro.setText("Registro Usuarios");
        menu_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_registroActionPerformed(evt);
            }
        });
        menu_file.add(menu_registro);

        jMenuBar1.add(menu_file);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void btn_login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_adminActionPerformed
          
            
    }//GEN-LAST:event_btn_login_adminActionPerformed

    private void txt_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dniActionPerformed

    private void menu_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_registroActionPerformed
        
    }//GEN-LAST:event_menu_registroActionPerformed

    private void btn_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnoActionPerformed
    
    
    
    
    }//GEN-LAST:event_btn_alumnoActionPerformed

    private void btn_login_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_alumnoActionPerformed
        
    }//GEN-LAST:event_btn_login_alumnoActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        
    }//GEN-LAST:event_btn_adminActionPerformed

    private void txt_legajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_legajoKeyTyped
        char c;
        c = evt.getKeyChar();
        if((c<'0' || c>'9'))
            evt.consume();
    }//GEN-LAST:event_txt_legajoKeyTyped

    private void txt_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniKeyTyped
        char c;
        c = evt.getKeyChar();
        if((c<'0' || c>'9'))
            evt.consume();
    }//GEN-LAST:event_txt_dniKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char c;
        c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ') )
            evt.consume();
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        char c;
        c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ') )
            evt.consume();
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void txt_legajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_legajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_legajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_admin;
    public javax.swing.JButton btn_alumno;
    public javax.swing.JButton btn_login_admin;
    public javax.swing.JButton btn_login_alumno;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JLabel lbl_admin;
    public javax.swing.JLabel lbl_alumno;
    public javax.swing.JLabel lbl_apellido;
    public javax.swing.JLabel lbl_contra;
    public javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_fondo;
    public javax.swing.JLabel lbl_legajo;
    public javax.swing.JLabel lbl_nombre;
    private javax.swing.JMenu menu_file;
    public javax.swing.JMenuItem menu_registro;
    public javax.swing.JTextField txt_apellido;
    public javax.swing.JPasswordField txt_contra;
    public javax.swing.JTextField txt_dni;
    public javax.swing.JTextField txt_legajo;
    public javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
