/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Elias
 */
public class VistaMateriasAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaProfesores
     */
    public VistaMateriasAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_materias = new javax.swing.JTable();
        sp_idprofesor = new javax.swing.JSpinner();
        btn_cambiar = new javax.swing.JButton();
        sp_idmateria = new javax.swing.JSpinner();
        txt_cupos = new javax.swing.JTextField();
        txt_horarios = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_menu = new javax.swing.JMenuItem();
        menu_profesores = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idMateria", "Materia", "idProfesor", "Nombre", "Apellido", "Horarios", "Cupos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_materias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 610, 350));
        getContentPane().add(sp_idprofesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        btn_cambiar.setText("Cambiar");
        getContentPane().add(btn_cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 100, -1));
        getContentPane().add(sp_idmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));
        getContentPane().add(txt_cupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 60, -1));
        getContentPane().add(txt_horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 60, -1));

        jLabel1.setText("idProfesor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 70, -1));

        jLabel2.setText("idMateria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 60, -1));

        jLabel3.setText("Cupos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        jLabel4.setText("Horarios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jMenu1.setText("Volver ");
        jMenu1.setActionCommand("Volver");

        menu_menu.setText("Volver al Menú");
        jMenu1.add(menu_menu);

        menu_profesores.setText("Ir a Profesores");
        jMenu1.add(menu_profesores);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sesión");

        menu_cerrar.setText("Cerrar Sesión");
        jMenu2.add(menu_cerrar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMateriasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMateriasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMateriasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMateriasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMateriasAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cambiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JMenuItem menu_cerrar;
    public javax.swing.JMenuItem menu_menu;
    public javax.swing.JMenuItem menu_profesores;
    public javax.swing.JSpinner sp_idmateria;
    public javax.swing.JSpinner sp_idprofesor;
    public javax.swing.JTable tb_materias;
    public javax.swing.JTextField txt_cupos;
    public javax.swing.JTextField txt_horarios;
    // End of variables declaration//GEN-END:variables
}
